### ISSUE TITLE
Bug with auto-reply if player AFK

### ISSUE THREAD

**Issue by ghost** [Agzam4/Mindustry-mod#8]
> [!IMPORTANT]
> ![Screenshot from 2024-09-22 15-05-07](https://github.com/user-attachments/assets/a05cd1ba-fdc3-4b00-8cd0-5bca9a77e796)

:dependabot: How to reproduce the bug:
1. Mention player
2. Write a message '@\_players_name _code\_'
> [!WARNING]
> After the _code_ field, *DO NOT* write anything :shipit:

**Comment by ghost** [comment]
```
[I] Disconnecting.
[E] java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(SystemTray.java:180)
	at agzam4.Awt.message(Awt.java:37)
	at agzam4.AgzamMod.lambda$init$17(AgzamMod.java:299)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.core.NetClient.sendMessage(NetClient.java:209)
	at mindustry.gen.SendMessageCallPacket2.handleClient(SendMessageCallPacket2.java:40)
	at mindustry.net.Net.handleClientReceived(Net.java:293)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:194)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
